// Code generated by go-swagger; DO NOT EDIT.

package peers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AddTransactionCreatedCode is the HTTP code returned for type AddTransactionCreated
const AddTransactionCreatedCode int = 201

/*AddTransactionCreated transaction commited

swagger:response addTransactionCreated
*/
type AddTransactionCreated struct {
}

// NewAddTransactionCreated creates AddTransactionCreated with default headers values
func NewAddTransactionCreated() *AddTransactionCreated {

	return &AddTransactionCreated{}
}

// WriteResponse to the client
func (o *AddTransactionCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// AddTransactionBadRequestCode is the HTTP code returned for type AddTransactionBadRequest
const AddTransactionBadRequestCode int = 400

/*AddTransactionBadRequest invalid transaction

swagger:response addTransactionBadRequest
*/
type AddTransactionBadRequest struct {
}

// NewAddTransactionBadRequest creates AddTransactionBadRequest with default headers values
func NewAddTransactionBadRequest() *AddTransactionBadRequest {

	return &AddTransactionBadRequest{}
}

// WriteResponse to the client
func (o *AddTransactionBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
