// Code generated by go-swagger; DO NOT EDIT.

package peers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetChainHandlerFunc turns a function with the right signature into a get chain handler
type GetChainHandlerFunc func(GetChainParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetChainHandlerFunc) Handle(params GetChainParams) middleware.Responder {
	return fn(params)
}

// GetChainHandler interface for that can handle valid get chain params
type GetChainHandler interface {
	Handle(GetChainParams) middleware.Responder
}

// NewGetChain creates a new http.Handler for the get chain operation
func NewGetChain(ctx *middleware.Context, handler GetChainHandler) *GetChain {
	return &GetChain{Context: ctx, Handler: handler}
}

/*GetChain swagger:route GET /chain peers getChain

Retrieve the entire chain of blocks

*/
type GetChain struct {
	Context *middleware.Context
	Handler GetChainHandler
}

func (o *GetChain) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetChainParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
