// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// RegisterWithNodeHandlerFunc turns a function with the right signature into a register with node handler
type RegisterWithNodeHandlerFunc func(RegisterWithNodeParams) middleware.Responder

// Handle executing the request and returning a response
func (fn RegisterWithNodeHandlerFunc) Handle(params RegisterWithNodeParams) middleware.Responder {
	return fn(params)
}

// RegisterWithNodeHandler interface for that can handle valid register with node params
type RegisterWithNodeHandler interface {
	Handle(RegisterWithNodeParams) middleware.Responder
}

// NewRegisterWithNode creates a new http.Handler for the register with node operation
func NewRegisterWithNode(ctx *middleware.Context, handler RegisterWithNodeHandler) *RegisterWithNode {
	return &RegisterWithNode{Context: ctx, Handler: handler}
}

/*RegisterWithNode swagger:route POST /register_with registerWithNode

Register with a specific node

*/
type RegisterWithNode struct {
	Context *middleware.Context
	Handler RegisterWithNodeHandler
}

func (o *RegisterWithNode) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRegisterWithNodeParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
