// Code generated by go-swagger; DO NOT EDIT.

// Package restapi GoChain
//
//  GoChain API
//  Schemes:
//    http
//  Host: localhost:3000
//  BasePath: /v1
//  Version: 1.0.0
//  License: WTFPL
//  Contact: <m.lyamets@innopolis.ru>
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
